[build]
  # Build command
  command = "npm run build"
  
  # Directory with the static build output
  publish = "dist"

[build.environment]
  # Node.js version and CI settings
  NODE_VERSION = "18"
  CI = "false"

[[redirects]]
  # Handle client-side routing for React Router
  from = "/*"
  to = "/index.html"
  status = 200
  
[[headers]]
  # Security headers
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  # Cache static assets
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  # Cache control for index.html
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"